# Basic
title: EthanX's Blog
subtitle: 夫君子之行，静以修身，俭以养德。
welcome_message:
description: 嗨，我叫许德鸿，是一名iOS开发者，目前就职于国信证券。欢迎来到我的博客，一起交流技术，共同学习。
creator: EthanX

url: "http://ethanx.me"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color:

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 访问博客

# Navigation buttons in the front page.
nav:
    - {title: 简历, description: 查看博主简历, url: 'https://github.com/XuDeHong/my-resume/blob/master/个人简历pdf版.pdf'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: EthanX
    # duoshuo:

# Social
social:
    github: XuDeHong
    mail: DeHongBoy@outlook.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
